
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-update
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-update
  template:
    metadata:
      labels:
        app: user-update
    spec:
      containers:
      - name: user-update
        image: user-update:latest
        ports:
        - containerPort: 8080
        env:
        - name: BRANCHNAME
          value: "PROD"
        - name: DEPLOYENV
          value: "PROD"
        - name: VERSION
          value: "1.0"